language: ruby
rvm:
- 2.2.3
script:
- bundle install
- bundle exec rake db:create db:schema:load
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: Lp4khIR1/SnF8uJBhPcl7bQ/zgmLGnGUUec9YNr0lwAUQ/ZFJ46UqWbvF9aGYfGSUVMJMTPlgPA5259NObRQB2y/QBOBfWr0vqUsUJoFa+6wFg+PF353KDZ2Q+5rgYYl6SgsFVUk7Sfy4INAUACTQgnUpl+e4sGLBj88saQJsM+WHgiB3+rAO7VAuRtkildxEiWYce+1FeFG5OVebxLJwmq2lNf2C1B8jHXp0lug1Mg0xHU2AgfiNl/F9PsAPq9d9ABe4TB83grN20b66MuNyxHpae8wk7fVfRt3jJlJ12rxdye+o8DixaH5eXi54B9V7pstMDxL1QtaxSSxKMDNkz+AosW1WsDkQCjsnAyHrmXxbz+pxYqzTQ0cN+2YUOynq2XUa4GsEkZVtiLchyCAKz5hXmXIBOgB/iUPF0mofvtwAJs9GyKfBDrEQXMOSai1pkV/ilQdKYQ2Z1GSLc/DhuT5yNE72+CdKUsn1k1eme8h/OrWvvfazbN7ff1P6tjAstiS4IIMLWFjR2z76N5w5D9YMHRJArYEGBN2MbJ2rTcpBZNinh2Zc16EYLj7GKQ1M1+jx7dDNspNbi0oOCWn0bF5J2PvnwrPpgHdB+AU/SIdK7CCKW7mNS1U4GoBIqGj3Cl8XDz3eSTP8iPvEulNzWOMww44vKFngLW/hLu9338=
  app: denvermeetings
