language: ruby
rvm:
- 2.6.0
services:
- postgresql
before_script:
- cp ./config/travis.database.yml ./config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle install
- bundle exec rake db:reset
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: "d3l0RNhz5d05SZ8YzprZjSU9izBTmGOK522Bb9mZk9sKT6cmHj1mjrCIk5mat6xPVk/KpLBd88n45ViReCQxMyXWioAGgBKpEXgtCpSURGpaxQBnJQd1MK4pndRgLOPE3h6ZomhhyTg1jdRD72sHq899P+u7sOF+eMth8bt0laGFCvofoR0rVGuCFymD0WDkU8L629BhMVim6O6XnhSsvQapHmxKkZ6PNh91IthHqHL7Faboo/QQB5eTdgK9baMLj+bMi7lQ7+fw5MNoNVt4htaYrPeEXcbgNCrDXMuAACybKk30peVhJ7INZwMpYVdQDYC63AJ77o8mf2SpT5Bj4ROd2pKSJTAyHzfrO4UMDUlmAbUu6PfWfhA7BBFtswn6iPyH9zTUx9/dd2tz6KcJQSPLfAMmbgvm2XmyLsojHo0AJb9nnxSFnnuHRxGO1A2HDv85G4gjiPyMcVx68fWiZOL9yyWarOaDDcrpMIyw7tkORhSMn3StuzGgzo0TDZmrhGI6kV8UXI4/C9y/gWtHX8lkePpQ9yvK9vkxlERE1xNQBS6v6H2Raa8eRGP+R2fF9jKqWTX5F0NXS7PkX47ta6UO+teoRL2pkWZBHnZdjSLwWvv4uqDOPt0mVosQJ2yPEca7T3Y6D1X58oJKOAsrZnl86OWnjhewMigepvdne/g="
  app: denvermeetings
