default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: denver-meetings_development

test:
  <<: *default
  database: denver-meetings_test

production:
  <<: *default
  database: denver-meetings_production
